In [3]:
import pandas as pd
import numpy as np 
from pandas import Series,DataFrame

## Concatenate in numpy 

In [6]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.concatenate((arr,arr))  # by default works on axis=0 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.concatenate((arr,arr),axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

# Concatenate in Pandas 

In [14]:
ser1 = Series(np.arange(2),index=['a','b'])

In [19]:
ser2 = Series(10 + np.arange(2),index=['c','d'])

In [20]:
ser3 = Series(20 + np.arange(2),index=['e','f'])

In [22]:
pd.concat([ser1,ser2,ser3]) # By default axis=0

a     0
b     1
c    10
d    11
e    20
f    21
dtype: int64

In [23]:
pd.concat([ser1,ser2,ser3],axis=1)

0     1     2
a  0.0   NaN   NaN
b  1.0   NaN   NaN
c  NaN  10.0   NaN
d  NaN  11.0   NaN
e  NaN   NaN  20.0
f  NaN   NaN  21.0

In [27]:
# to identify from which series the data is taken we pass a funtion key()
pd.concat([ser1,ser2,ser3],keys=['from 1st series','from 2nd series','from 3rd series']) 

from 1st series  a     0
                 b     1
from 2nd series  c    10
                 d    11
from 3rd series  e    20
                 f    21
dtype: int64

In [30]:
# if we pass axis=1 then the keys argumets will be columns headers 

pd.concat([ser1,ser2,ser3],axis=1,keys=['from 1st series','from 2nd series','from 3rd series'])

from 1st series  from 2nd series  from 3rd series
a              0.0              NaN              NaN
b              1.0              NaN              NaN
c              NaN             10.0              NaN
d              NaN             11.0              NaN
e              NaN              NaN             20.0
f              NaN              NaN             21.0

In [31]:
## Same logic is dataframes

In [41]:
df1 = DataFrame(np.arange(4).reshape(2,2),
               index=['a','b'],
               columns=['col1','col2'])
df1

col1  col2
a     0     1
b     2     3

In [49]:
df2 = DataFrame(10 + np.arange(4).reshape(2,2),
               index=['a','d'],
               columns=['col1','col2'])

df2

col1  col2
a    10    11
d    12    13

In [50]:
pd.concat([df1,df2])

col1  col2
a     0     1
b     2     3
a    10    11
d    12    13

In [55]:
pd.concat([df1,df2],axis=1,keys=['from df1','from df2'],names=['index','columns'])

index   from df1      from df2      
columns     col1 col2     col1  col2
a            0.0  1.0     10.0  11.0
b            2.0  3.0      NaN   NaN
d            NaN  NaN     12.0  13.0