In [1]:
import numpy as np

In [3]:
lst = [i for i in range(12)]
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [11]:
arr_1 = np.array(lst)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr_1.dtype

dtype('int32')

In [16]:
np.zeros(13)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [19]:
# you have to pass tuple for 2,3 array 

np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
np.empty(23)  # retunns garbage value

array([  6.79038653e-313,   2.35541533e-312,   6.79038654e-313,
         2.05833592e-312,   2.14321575e-312,   2.46151512e-312,
         6.79038654e-313,   2.05833592e-312,   2.44029516e-312,
         2.46151512e-312,   2.37663529e-312,   2.14321575e-312,
         2.12199579e-313,   2.33419537e-312,   9.76118064e-313,
         2.14321575e-312,   2.35541533e-312,   8.48798317e-313,
         1.03977794e-312,   1.08221785e-312,   8.70018274e-313,
         2.56765133e-312,   3.91792476e-317])

In [27]:
np.arange(23) # just like range function but return an array instead of list 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [33]:
 np.ones((2,3))


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [46]:
np.eye((3))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])