In [1]:
import numpy as np 

In [3]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr[:3]


array([0, 1, 2])

In [13]:
arr[4:8]

array([4, 5, 6, 7])

In [20]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) # for 2d array have to pass list of list 
                                                #or np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr_2d[2][0]

7

In [47]:
arr_2d[1,2]

6

In [53]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [55]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [56]:
arr_2d[0:,:1]

array([[1],
       [4],
       [7]])

# Fancy Indexing

In [71]:
arr_3d = np.empty((8,4))
arr_3d.shape[0]       # axis 0 --> Row
                        # axis 1 -- > Column

8

In [72]:
for row in range(8):
    arr_3d[row] = row

In [74]:
arr_3d

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [77]:
arr_3d[2,2]  # arr_3d[axis0,axis1 ]

2.0

In [81]:
arr_3d[[1,4]]  # to get a subset of rows in a particular order

array([[ 1.,  1.,  1.,  1.],
       [ 4.,  4.,  4.,  4.]])

In [83]:
arr_3 = np.arange(32).reshape((8,4))
arr_3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [90]:
arr_3[[3,4],[3]]

array([15, 19])

In [91]:
np.random.rand(10)

array([ 0.21202904,  0.1955488 ,  0.80872314,  0.32537404,  0.42105321,
        0.27436883,  0.36554098,  0.49081193,  0.39784137,  0.53420623])

In [106]:
np.random.randn(10)

array([-0.92980174, -0.96624703,  0.55901378,  1.31047151, -0.82488528,
       -0.51603195, -1.60992773, -0.87021561,  0.28579608,  0.51561101])

In [107]:
np.random.random_integers(0,10+1)

C:\Users\shubham\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 11 + 1) instead
  """Entry point for launching an IPython kernel.


1